name: Sync Team Spirit Matches

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (adjust as needed)
  workflow_dispatch:       # Allow manual trigger

jobs:
  sync-matches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        run: python main.py
